### ISSUE TITLE
Anonymous contestants are displayed

### ISSUE THREAD

**Issue by Eliclax** [shino-sky/mods-website#1]
Anonymous contestants display on monthly contest overview webpages, but there is no name attached to them

**Comment by shino16** [comment]
Can I ask where it is? I think anonymous participants are excluded from the "individual results" table.

**Comment by Eliclax** [comment]
They should be on there, marked with a "■"

**Comment by shino16** [comment]
Ah by "individual results" table I meant https://shino-sky.github.io/mods-website/timeline/Feb.2020/individual
Those anonymous contestants who are marked with ■ on the spreadsheet are not on the page, are they?

**Comment by shino16** [comment]
Now they are split:  5625718c
