### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Eliclax** [shino-sky/mods-website#13]
A few small things:
1. Change "About MODS" to "MODS Discord Guide" in the header
2. Can you link "Mathematical Olympiads Discord Server" in the first paragraph to this link: https://discord.gg/q93Wrgn
3. Can you delete "larger" before the "International Science Olympiad Discord Network" in the second paragraph XD
4. Can you link "International Science Olympiad Discord Network" to https://discord.gg/KCdTTF5
5. In the third paragraph can you link "donating via Patreon" to the same link as the "Donate" button in the footer?
6. Replace the first sentence with "This website, kindly developed by shino, has been made possible by ipho-unofficial.org's open source Github, imo-official.org, and the financial support from our generous Patreons." Include the link to ipho-unofficial.org, imo-official.org, and you can also include a link to your Github profile on your name if you want XD
7. At the end of the third paragraph can you add "If you have a suggestion for this website or find a bug, please message Staff Mail on Discord, or submit a new issue on our Github." with a link to our Github repo on the "Github".

**Comment by shino16** [comment]
Very cool! Done in 16f5a906
