### ISSUE TITLE
Display anonymous participations on contestant page

### ISSUE THREAD

**Issue by Eliclax** [shino-sky/mods-website#15]
On each contestant's page, display all the contests they participated in, even if it was anonymous. Maybe just display the scores and total column with a slash like you've done with the UserID and Username column in the contest pages?

**Comment by shino16** [comment]
Is this fine?
![image](https://user-images.githubusercontent.com/40788005/79641298-9cfa0380-81d1-11ea-8637-33bd0422a279.png)

**Comment by Eliclax** [comment]
Ohh if you already have the text under it then we probably don't need the slashes haha. I think the text by itself looks better

**Comment by shino16** [comment]
Oops, definitely true
![image](https://user-images.githubusercontent.com/40788005/79641489-cebf9a00-81d2-11ea-9915-ef03516c791c.png)
