### ISSUE TITLE
Timeline and dashes :P

### ISSUE THREAD

**Issue by Eliclax** [shino-sky/mods-website#16]
1. Can you format each date so it shows 11–12 Apr instead of Apr-11 - Apr-12? Note that to denote a range like 11–12 you should use an en-dash :P
2. Can you change the name of each contest so that in between the "2020-01" and the "Beginner" part there's a em-dash "—"?

**Comment by shino16** [comment]
Wow, thanks
Should there be a space between "–" and the next word?

**Comment by Eliclax** [comment]
Oh yeah, so the final thing should look like this:
"2020-01 — Beginner"

**Comment by shino16** [comment]
Done (8658914). I didn't even know there are two dashes 😇

**Comment by Eliclax** [comment]
Yay, looks great now! :D

There are actually a lot more than two dashes though :P there's the en-dash, em-dash, figure dash, swung dash, not to mention other similar characters like hyphen, tilde, horizontal bar, minus sign, hyphen-minus, etc. You can check this Wikipedia article hahaha https://en.wikipedia.org/wiki/Dash

**Comment by shino16** [comment]
Awww😵
– This is interesting and helpful, thanks ^^
