### ISSUE TITLE
Make a summary of scores?

### ISSUE THREAD

**Issue by Eliclax** [shino-sky/mods-website#18]
On the page for each contest, is it possible to add a table showing how many people got each score for each problem, and also the averages and standard deviations of each problem? Kind of like https://www.imo-official.org/year_statistics.aspx?year=2019 but without the graphs and correlations XD

**Comment by shino-sky** [comment]
![Uploading image.png…]()

**Comment by shino16** [comment]
I think It's ready to push!

![image](https://user-images.githubusercontent.com/40788005/79686554-2bc35a80-827c-11ea-94fc-6db18e992057.png)

**Comment by shino16** [comment]
Implemented in 576730c55a3e490cd22f75158d0bcb5531c779c1
Now it's out!
