### ISSUE TITLE
Change in anonymous representation

### ISSUE THREAD

**Issue by Eliclax** [shino-sky/mods-website#19]
I realised that some people had requested anonymity but not been granted it (because they were in the top 3, for example), and I had not removed their status of anonymity from the database, so on the website they appear as anonymous even though they're not supposed to be.

I have changed these contestants from having a "Yes" in their anonymous column to a "Req" for requested. Can you treat "Req" as blank is the cell was blank?

**Comment by shino16** [comment]
Okay, now "Req" is handled as a blank.
