### ISSUE TITLE
Contestant List cannot be sorted

### ISSUE THREAD

**Issue by boboquack** [shino-sky/mods-website#20]
The list [here](https://shino-sky.github.io/publish-mods-website/contestants/) is by UserID which is pretty arbitrary. Some sorting functionality would be helpful.

**Comment by shino16** [comment]
Thanks for the suggestion! I'll have it sorted by the number of gold medals, silver, then bronze.

**Comment by shino16** [comment]
It's done, now I'm planning to add some feature to support sorting by the specified column as well.
