### ISSUE TITLE
If you sort by contestant it sorts by id

### ISSUE THREAD

**Issue by IcosahedralDice** [shino-sky/mods-website#25]
![image](https://user-images.githubusercontent.com/39070658/83814954-604b8280-a713-11ea-8718-dd32630cdc73.png)
![image](https://user-images.githubusercontent.com/39070658/83814970-680b2700-a713-11ea-9ce0-ab86acd7bee7.png)

**Comment by shino16** [comment]
Thank you for pointing this out, I'll fix it now
