### ISSUE TITLE
Header/footer changes

### ISSUE THREAD

**Issue by Eliclax** [shino-sky/mods-website#26]
1. After releasing the results for each contest, the second line should read "\<just released contest\> • \<next contest\>". I have updated the database to include the timeslots of the contests for the next few months.
2. Change "MODS Discord Guide" in header to "MODS Discord Guide (pdf)
3. Change "Join us!" in footer to "Join our server!"

**Comment by shino16** [comment]
Cool!
I pushed the changes, please check if it looks as expected 😀
