### ISSUE TITLE
Insert "Donate" in footer

### ISSUE THREAD

**Issue by Eliclax** [shino-sky/mods-website#4]
A "Donate" button in the footer, linking to the Patreon.

**Comment by shino16** [comment]
Now I added a link to http://bit.ly/MODS_patreon in the footer.
![image](https://user-images.githubusercontent.com/40788005/78513347-d734cf80-77e5-11ea-9854-6c2510524464.png)

**Comment by shino16** [comment]
and it's published. https://shino-sky.github.io/publish-mods-website/
